"""
Pydantic Schemas for Request & Response Validation
"""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict

class VitalsInput(BaseModel):
    systolic_bp: Optional[float] = Field(None, ge=40, le=300, description="Systolic Blood Pressure (mmHg)")
    diastolic_bp: Optional[float] = Field(None, ge=20, le=200, description="Diastolic Blood Pressure (mmHg)")
    heart_rate: Optional[float] = Field(None, ge=20, le=300, description="Heart Rate (BPM)")
    temperature_f: Optional[float] = Field(None, ge=80, le=115, description="Body Temperature (°F)")
    spo2: Optional[float] = Field(None, ge=40, le=100, description="Oxygen Saturation (%)")
    respiratory_rate: Optional[float] = Field(None, ge=4, le=80, description="Respiratory Rate (Breaths/min)")


class TriageAssessmentRequest(BaseModel):
    """Input payload for generating non-diagnostic triage prioritization."""
    age: int = Field(..., ge=0, le=130, description="Patient age in years")
    gender: str = Field(..., description="Gender: Male, Female, Other")
    chief_complaint: str = Field(..., min_length=2, description="Primary presenting symptom")
    symptom_details: Optional[str] = Field("", description="Detailed narrative of symptoms")
    duration: Optional[str] = Field("", description="Duration of symptoms")
    vitals: Optional[VitalsInput] = None
    allergies: Optional[str] = Field("", description="Known allergies or None")
    past_medical_history: Optional[str] = Field("", description="Known chronic conditions")
    extracted_report_text: Optional[str] = Field("", description="OCR extracted text from medical/lab reports")


class TriageAssessmentResponse(BaseModel):
    """Output generated by the modular AI/heuristic triage engine."""
    triage_category: int = Field(..., ge=1, le=4, description="1=Immediate, 2=Very Urgent, 3=Urgent, 4=Routine")
    triage_category_label: str = Field(..., description="E.g. Immediate / Resuscitation")
    triage_category_color: str = Field(..., description="red, orange, yellow, green")
    triage_summary: str = Field(..., description="Structured non-diagnostic clinical summary note")
    clinical_flags: List[str] = Field(default_factory=list, description="Immediate vital or symptom warning flags")
    missing_information: List[str] = Field(default_factory=list, description="Critical data points absent from intake")
    follow_up_questions: List[str] = Field(default_factory=list, description="Targeted screening questions for health workers")
    disclaimer: str = Field(
        "NON-DIAGNOSTIC NOTICE: This triage summary is generated to organize clinical intake information "
        "and assist qualified medical personnel with review prioritization. It is NOT a medical diagnosis, "
        "does NOT prescribe treatments, and does NOT replace licensed healthcare professionals."
    )


class PatientCreate(BaseModel):
    patient_identifier: Optional[str] = None
    full_name: str = Field(..., min_length=2)
    age: int = Field(..., ge=0, le=130)
    gender: str
    contact_phone: Optional[str] = ""
    location: Optional[str] = ""


class PatientResponse(BaseModel):
    id: int
    patient_identifier: str
    full_name: str
    age: int
    gender: str
    contact_phone: Optional[str]
    location: Optional[str]
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class TriageRecordCreate(BaseModel):
    """Complete intake submission to save both patient & triage assessment."""
    patient: PatientCreate
    chief_complaint: str
    symptom_details: Optional[str] = ""
    duration: Optional[str] = ""
    vitals: Optional[VitalsInput] = None
    allergies: Optional[str] = ""
    past_medical_history: Optional[str] = ""
    report_filename: Optional[str] = None
    extracted_report_text: Optional[str] = None


class ReviewerUpdate(BaseModel):
    """Doctor or qualified health worker review update."""
    reviewer_status: str = Field(..., description="PENDING, IN_REVIEW, COMPLETED")
    reviewer_notes: Optional[str] = None
    reviewed_by: str = Field(..., min_length=2)
    confirmed_category: Optional[int] = Field(None, ge=1, le=4)


class TriageRecordResponse(BaseModel):
    id: int
    patient_id: int
    patient: Optional[PatientResponse] = None
    chief_complaint: str
    symptom_details: Optional[str]
    duration: Optional[str]
    systolic_bp: Optional[float]
    diastolic_bp: Optional[float]
    heart_rate: Optional[float]
    temperature_f: Optional[float]
    spo2: Optional[float]
    respiratory_rate: Optional[float]
    allergies: Optional[str]
    past_medical_history: Optional[str]
    report_filename: Optional[str]
    extracted_report_text: Optional[str]
    triage_category: int
    triage_category_label: str
    triage_category_color: str
    triage_summary: str
    missing_information: List[str]
    follow_up_questions: List[str]
    clinical_flags: List[str]
    reviewer_status: str
    reviewer_notes: Optional[str]
    reviewed_by: Optional[str]
    reviewed_at: Optional[datetime]
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
